# Form implementation generated from reading ui file 'reco_page.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from heartCheckBox import HeartCheckBox


class Ui_RecoPage(object):
    def setupUi(self, RecoPage):
        RecoPage.setObjectName("RecoPage")
        RecoPage.resize(890, 640)
        RecoPage.setStyleSheet("background-color: #F0F0F0;")

        self.like_user_4 = HeartCheckBox(parent=RecoPage)
        self.like_user_4.setEnabled(True)
        self.like_user_4.setGeometry(QtCore.QRect(650, 450, 61, 25))
        self.like_user_4.setObjectName("like_user_4")

        self.like_user_1 = HeartCheckBox(parent=RecoPage)
        self.like_user_1.setEnabled(True)
        self.like_user_1.setGeometry(QtCore.QRect(650, 180, 61, 25))
        self.like_user_1.setObjectName("like_user_1")

        self.like_user_2 = HeartCheckBox(parent=RecoPage)
        self.like_user_2.setEnabled(True)
        self.like_user_2.setGeometry(QtCore.QRect(650, 270, 61, 25))
        self.like_user_2.setObjectName("like_user_2")

        self.like_user_3 = HeartCheckBox(parent=RecoPage)
        self.like_user_3.setEnabled(True)
        self.like_user_3.setGeometry(QtCore.QRect(650, 360, 61, 25))
        self.like_user_3.setObjectName("like_user_3")

        self.accroche = QtWidgets.QTextBrowser(parent=RecoPage)
        self.accroche.setGeometry(QtCore.QRect(530, 80, 251, 31))
        self.accroche.setObjectName("accroche")

        self.user_reco_1 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.user_reco_1.setGeometry(QtCore.QRect(530, 140, 301, 31))
        self.user_reco_1.setObjectName("user_reco_1")

        self.user_reco_2 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.user_reco_2.setGeometry(QtCore.QRect(530, 230, 301, 31))
        self.user_reco_2.setObjectName("user_reco_2")

        self.user_reco_3 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.user_reco_3.setGeometry(QtCore.QRect(530, 320, 301, 31))
        self.user_reco_3.setObjectName("user_reco_3")

        self.user_reco_4 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.user_reco_4.setGeometry(QtCore.QRect(530, 410, 301, 31))
        self.user_reco_4.setObjectName("user_reco_4")

        self.user_reco_5 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.user_reco_5.setGeometry(QtCore.QRect(530, 500, 301, 31))
        self.user_reco_5.setObjectName("user_reco_5")

        self.like_user_5 = HeartCheckBox(parent=RecoPage)
        self.like_user_5.setEnabled(True)
        self.like_user_5.setGeometry(QtCore.QRect(650, 540, 61, 25))
        self.like_user_5.setObjectName("like_user_5")

        self.like_sim_1 = HeartCheckBox(parent=RecoPage)
        self.like_sim_1.setEnabled(True)
        self.like_sim_1.setGeometry(QtCore.QRect(400, 180, 61, 25))
        self.like_sim_1.setObjectName("like_sim_1")

        self.origine_1 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.origine_1.setGeometry(QtCore.QRect(10, 170, 221, 31))
        self.origine_1.setObjectName("origine_1")

        self.reco_sim_1 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.reco_sim_1.setGeometry(QtCore.QRect(10, 130, 461, 31))
        self.reco_sim_1.setObjectName("reco_sim_1")

        self.like_sim_2 = HeartCheckBox(parent=RecoPage)
        self.like_sim_2.setEnabled(True)
        self.like_sim_2.setGeometry(QtCore.QRect(400, 270, 61, 25))
        self.like_sim_2.setObjectName("like_sim_2")

        self.origine_2 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.origine_2.setGeometry(QtCore.QRect(10, 260, 221, 31))
        self.origine_2.setObjectName("origine_2")

        self.reco_sim_2 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.reco_sim_2.setGeometry(QtCore.QRect(10, 220, 461, 31))
        self.reco_sim_2.setObjectName("reco_sim_2")

        self.like_sim_3 = HeartCheckBox(parent=RecoPage)
        self.like_sim_3.setEnabled(True)
        self.like_sim_3.setGeometry(QtCore.QRect(400, 360, 61, 25))
        self.like_sim_3.setObjectName("like_sim_3")

        self.origine_3 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.origine_3.setGeometry(QtCore.QRect(10, 350, 221, 31))
        self.origine_3.setObjectName("origine_3")

        self.reco_sim_3 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.reco_sim_3.setGeometry(QtCore.QRect(10, 310, 461, 31))
        self.reco_sim_3.setObjectName("reco_sim_3")

        self.like_sim_4 = HeartCheckBox(parent=RecoPage)
        self.like_sim_4.setEnabled(True)
        self.like_sim_4.setGeometry(QtCore.QRect(400, 450, 61, 25))
        self.like_sim_4.setObjectName("like_sim_4")

        self.origine_4 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.origine_4.setGeometry(QtCore.QRect(10, 440, 221, 31))
        self.origine_4.setObjectName("origine_4")

        self.reco_sim_4 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.reco_sim_4.setGeometry(QtCore.QRect(10, 400, 461, 31))
        self.reco_sim_4.setObjectName("reco_sim_4")

        self.like_sim_5 = HeartCheckBox(parent=RecoPage)
        self.like_sim_5.setEnabled(True)
        self.like_sim_5.setGeometry(QtCore.QRect(400, 540, 61, 25))
        self.like_sim_5.setObjectName("like_sim_5")

        self.origine_5 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.origine_5.setGeometry(QtCore.QRect(10, 530, 221, 31))
        self.origine_5.setObjectName("origine_5")

        self.reco_sim_5 = QtWidgets.QTextBrowser(parent=RecoPage)
        self.reco_sim_5.setGeometry(QtCore.QRect(10, 490, 461, 31))
        self.reco_sim_5.setObjectName("reco_sim_5")

        self.recipe_name = QtWidgets.QLineEdit(parent=RecoPage)
        self.recipe_name.setGeometry(QtCore.QRect(10, 80, 289, 31))
        self.recipe_name.setAutoFillBackground(False)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.recipe_name.setFont(font)
        self.recipe_name.setText("")
        self.recipe_name.setObjectName("recipe_name")

        self.go = QtWidgets.QPushButton(parent=RecoPage)
        self.go.setEnabled(True)
        self.go.setGeometry(QtCore.QRect(310, 80, 89, 31))
        self.go.setMinimumSize(QtCore.QSize(89, 0))
        self.go.setStyleSheet("QPushButton { background-color: #22A170; color: #FFFFFF; }"
                      "QPushButton:hover { background-color: #1B8459; }"
                      "QPushButton:pressed { background-color: #13633D; }")
        self.go.setObjectName("go")

        self.spinBox = QtWidgets.QSpinBox(parent=RecoPage)
        self.spinBox.setGeometry(QtCore.QRect(410, 80, 59, 26))
        self.spinBox.setObjectName("spinBox")

        self.line = QtWidgets.QFrame(parent=RecoPage)
        self.line.setGeometry(QtCore.QRect(500, -60, 20, 731))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")

        self.lcdNumber_1 = QtWidgets.QLCDNumber(parent=RecoPage)
        self.lcdNumber_1.setGeometry(QtCore.QRect(530, 180, 64, 23))
        self.lcdNumber_1.setStyleSheet("QLCDNumber { color: #213F3D; border-color: #213F3D; background-color: #E5E8E8; }")
        self.lcdNumber_1.setObjectName("lcdNumber_1")

        self.lcdNumber_2 = QtWidgets.QLCDNumber(parent=RecoPage)
        self.lcdNumber_2.setGeometry(QtCore.QRect(530, 270, 64, 23))
        self.lcdNumber_2.setStyleSheet("QLCDNumber { color: #213F3D; border-color: #213F3D; background-color: #E5E8E8; }")
        self.lcdNumber_2.setObjectName("lcdNumber_2")

        self.lcdNumber_3 = QtWidgets.QLCDNumber(parent=RecoPage)
        self.lcdNumber_3.setGeometry(QtCore.QRect(530, 360, 64, 23))
        self.lcdNumber_3.setStyleSheet("QLCDNumber { color: #213F3D; border-color: #213F3D; background-color: #E5E8E8; }")
        self.lcdNumber_3.setObjectName("lcdNumber_3")

        self.lcdNumber_4 = QtWidgets.QLCDNumber(parent=RecoPage)
        self.lcdNumber_4.setGeometry(QtCore.QRect(530, 450, 64, 23))
        self.lcdNumber_4.setStyleSheet("QLCDNumber { color: #213F3D; border-color: #213F3D; background-color: #E5E8E8; }")
        self.lcdNumber_4.setObjectName("lcdNumber_4")

        self.lcdNumber_5 = QtWidgets.QLCDNumber(parent=RecoPage)
        self.lcdNumber_5.setGeometry(QtCore.QRect(530, 540, 64, 23))
        self.lcdNumber_5.setStyleSheet("QLCDNumber { color: #213F3D; border-color: #213F3D; background-color: #E5E8E8; }")
        self.lcdNumber_5.setObjectName("lcdNumber_5")

        self.go_2 = QtWidgets.QPushButton(parent=RecoPage)
        self.go_2.setEnabled(True)
        self.go_2.setGeometry(QtCore.QRect(790, 80, 89, 31))
        self.go_2.setMinimumSize(QtCore.QSize(89, 0))
        self.go_2.setStyleSheet("QPushButton { background-color: #22A170; color: #FFFFFF; }"
                      "QPushButton:hover { background-color: #1B8459; }"
                      "QPushButton:pressed { background-color: #13633D; }")
        self.go_2.setObjectName("go_2")
       

        self.retranslateUi(RecoPage)
        QtCore.QMetaObject.connectSlotsByName(RecoPage)

    def retranslateUi(self, RecoPage):
        _translate = QtCore.QCoreApplication.translate
        RecoPage.setWindowTitle(_translate("RecoPage", "Recommandations"))
        self.accroche.setHtml('<p style="font-family: \'Arial\'; font-size: 12pt;">D\'autres utilisateurs aiment aussi</p>')
        self.user_reco_1.setHtml('')
        self.user_reco_2.setHtml('')
        self.user_reco_3.setHtml('')
        self.user_reco_4.setHtml('')
        self.user_reco_5.setHtml('')
        self.origine_1.setHtml('<p style="font-family: \'Ubuntu\'; font-size: 10pt;">Origine</p>')
        self.reco_sim_1.setHtml('')
        self.origine_2.setHtml('<p style="font-family: \'Ubuntu\'; font-size: 10pt;">Origine</p>')
        self.reco_sim_2.setHtml('')
        self.origine_3.setHtml('<p style="font-family: \'Ubuntu\'; font-size: 10pt;">Origine</p>')
        self.reco_sim_3.setHtml('')
        self.origine_4.setHtml('<p style="font-family: \'Ubuntu\'; font-size: 10pt;">Origine</p>')
        self.reco_sim_4.setHtml('')
        self.origine_5.setHtml('<p style="font-family: \'Ubuntu\'; font-size: 10pt;">Origine</p>')
        self.reco_sim_5.setHtml('')
        self.recipe_name.setPlaceholderText(_translate("RecoPage", "Entrez une recette"))
        self.go.setText(_translate("RecoPage", "Go"))
        self.go_2.setText(_translate("RecoPage", "Actualiser"))